### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by DeltaEclipse** [Goorakh/ModelSwapperSkins#3]
If I knew anything about modding I would (try to) do it myself, but is there anyway to disable the Loader rig/suit that is present in all of the skins? Even better if you could get rid of just the box frame itself but keep the arms.

**Comment by Goorakh** [comment]
You can't get rid of just the frame since the arms and frame are part of the same model. The whole suit can be removed, but it just looks ugly without it, you might be able to do it with SkinDetailPicker though.

Neither of those will be added to this mod.
