### ISSUE TITLE
I don't understand how this works

### ISSUE THREAD

**Issue by QuantumMekanik9** [Goorakh/ModelSwapperSkins#6]
I'm aware that the skins are procedurally generated, but I can't seem to get anything to happen whenever I boot the game with this mod installed.  I've tried adding it to my modpack, adding it to a smaller modpack, running it with nothing else but the necessary framework mods, nothing works.  Is there something I'm missing?

**Comment by Goorakh** [comment]
You're not missing something, the mod hasn't been updated for SotS yet, and currently does not work.

It will be updated eventually.

**Comment by QuantumMekanik9** [comment]
Ah, I see.  I suppose it's just a matter of that update ITSELF, then, as I hadn't considered that due to not having purchased that DLC myself.  Thank you for responding so quickly!
